# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Testing matrix

on:
  push:
    branches: [ devel ]
  pull_request:
    branches: [ devel ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.8", "3.9", "3.10", "3.11"]

    steps:

    # git checkout
    - uses: actions/checkout@v4

    # Install uv
    - name: Install uv
      uses: astral-sh/setup-uv@v5
      with:
          python-version: ${{ matrix.python-version }}

    # Install library
    - name: Install the project
      run: uv sync --all-extras --dev

    # Run tests
    - name: Run tests
      # For example, using `pytest`
      run: uv run pytest datastock/tests
